# Generated by Django 4.1.6 on 2023-02-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
